grafana:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - grafana.apatsev.org.ru
vmsingle:
  enabled: false
vmcluster:
  enabled: true
  ingress:
    select:
      enabled: true
      ingressClassName: nginx
      hosts:
        - vmselect.apatsev.org.ru
alertmanager:
  config:
    route:
      receiver: "blackhole"
      group_by: ["alertname", "cluster"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
    receivers:
      - name: blackhole
      - name: telegram
        telegram_configs:
          - api_url: https://api.telegram.org
            send_resolved: true
            bot_token: "<BOT_TOKEN>"
            chat_id: "<CHAT_ID>"
            parse_mode: "HTML"
