apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo-rollouts.yaml
  - blackbox-exporter.yaml
  - cert-manager.yaml
  - chaos-mesh.yaml
  - descheduler.yaml
  - external-secrets.yaml
  - falco.yaml
  - flux-operator.yaml
  - gatekeeper.yaml
  - goldpinger.yaml
  - keda.yaml
  - prometheus-adapter.yaml
  - reloader.yaml
  - vector.yaml
  - victoria-logs.yaml
  - victoria-metrics.yaml
