apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  interval: 15m
  timeout: 15m
  targetNamespace: gatekeeper-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: gatekeeper
      version: "3.22.0"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      interval: 15m
  releaseName: gatekeeper
