apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector
  namespace: flux-system
spec:
  interval: 15m
  timeout: 15m
  targetNamespace: vector
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  chart:
    spec:
      chart: vector
      version: "0.51.0"
      sourceRef:
        kind: HelmRepository
        name: vector
        namespace: flux-system
      interval: 15m
  releaseName: vector
  values:
    role: Agent
    service:
      enabled: false
    serviceHeadless:
      enabled: false
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      sources:
        kubernetes_logs:
          type: kubernetes_logs
      sinks:
        vlogs:
          type: elasticsearch
          inputs:
            - kubernetes_logs
          endpoints:
            - http://vls-victoria-logs-single-server.vlogs.svc.cluster.local:9428/insert/elasticsearch/
          api_version: v8
          compression: gzip
          healthcheck:
            enabled: false
          query:
            _msg_field: message
            _time_field: timestamp
            _stream_fields: kubernetes.pod_name,kubernetes.pod_namespace,kubernetes.container_name
