# Упрощённая конфигурация для малой/нулевой нагрузки: vmsingle, 1 реплика компонентов.

grafana:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - grafana.apatsev.org.ru

# Один инстанс — достаточно без нагрузки. VMCluster отключён.
vmsingle:
  enabled: true
  ingress:
    select:
      enabled: true
      ingressClassName: nginx
      hosts:
        - vmselect.apatsev.org.ru


