# VictoriaMetrics K8s Stack: метрики, алерты, Grafana (VMCluster, vmalert, vmagent, Alertmanager).
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmks
  namespace: flux-system
spec:
  interval: 15m
  timeout: 10m
  targetNamespace: vmks
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.71.x"
      sourceRef:
        kind: HelmRepository
        name: vmks
        namespace: flux-system
      interval: 5m
  releaseName: vmks
  values:
    grafana:
      ingress:
        ingressClassName: nginx
        enabled: true
        hosts:
          - grafana.apatsev.org.ru
    vmsingle:
      enabled: true
      ingress:
        select:
          enabled: true
          ingressClassName: nginx
          hosts:
            - vmselect.apatsev.org.ru
